# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_IP }}  >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./app/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}:/home/danielf/danielfitzgerald.uk/app/
      
      # - name: Restart Web Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.PROD_IP }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       echo Do something on the server
      #       cd danielfitzgerald.uk/
      #       git pull origin main
      #       echo Checking if nginx container is already running
      #       if [ "$( docker container inspect -f '{{.State.Running}}' nginx )" == "true" ];
      #       then
      #         echo Nginx is running
      #         echo Building and reloading nginx
      #         docker-compose up --detach --build nginx
      #       else
      #         echo Nginx is not running
      #         echo Starting containers
      #         docker-compose up
      #       fi