# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        env:
          SSH_KEY: ${{ secrets.ORACLE_SSH_KEY }}
          PROD_IP: ${{ secrets.PROD_IP }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Adding ssh key
          ssh-add - <<< "$SSH_KEY"
          echo Connecting to prod server
          ssh danielf@$PROD_IP
          echo Pulling latest changes from branch main
          cd danielfitzgerald.uk/
          git pull origin main
          echo Checking if nginx container is already running
          if [ "$( docker container inspect -f '{{.State.Running}}' nginx )" == "true" ];
          then
            echo Nginx is running
            echo Building and reloading nginx
            docker-compose up --detach --build nginx
          else
            echo Nginx is not running
            echo Starting containers
            docker-compose up
          fi
          
